version: '3'

services:
  web:
    image: trafex/php-nginx
    ports:
      - "8000:8080"
    volumes:
      - ../backend:/var/www/
      - ../backend/public:/var/www/html
    depends_on:
      - db
    networks:
      - asknicely
  
  vue:
    build:
      context: ..
      dockerfile: docker/vue/Dockerfile
    ports:
      - "8080:80"
    volumes:
      - ../frontend:/app
    depends_on:
      - web
      - db
    networks:
      - asknicely
  db:
    image: mysql:8
    environment:
      MYSQL_DATABASE: asknicely 
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - db_data:/var/lib/mysql
      - ./mysql/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - asknicely

volumes:
    db_data:  

networks:
  asknicely:
    driver: bridge